{"uid":"d7dce9eb7ac6394c","name":"test_deploy","fullName":"tests.integration.test_charm#test_deploy","historyId":"c20a6e30f9eb9eadd6b1ef7e9ad2158c","time":{"start":1761227717909,"stop":1761227780192,"duration":62283},"description":"Deploy the charm together with related charms.\n\n    Assert on the unit status before any relations/configurations take place.\n    ","descriptionHtml":"<p>Deploy the charm together with related charms.</p>\n<pre><code>Assert on the unit status before any relations/configurations take place.\n</code></pre>\n","status":"broken","statusMessage":"requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","statusTrace":"Traceback (most recent call last):\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 787, in urlopen\n    response = self._make_request(\n               ^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 488, in _make_request\n    raise new_e\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 464, in _make_request\n    self._validate_conn(conn)\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 1093, in _validate_conn\n    conn.connect()\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/connection.py\", line 741, in connect\n    sock_and_verified = _ssl_wrap_socket_and_match_hostname(\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/connection.py\", line 920, in _ssl_wrap_socket_and_match_hostname\n    ssl_sock = ssl_wrap_socket(\n               ^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/util/ssl_.py\", line 460, in ssl_wrap_socket\n    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/util/ssl_.py\", line 504, in _ssl_wrap_socket_impl\n    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/ssl.py\", line 455, in wrap_socket\n    return self.sslsocket_class._create(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/ssl.py\", line 1042, in _create\n    self.do_handshake()\n  File \"/usr/lib/python3.12/ssl.py\", line 1320, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/requests/adapters.py\", line 644, in send\n    resp = conn.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 841, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/util/retry.py\", line 474, in increment\n    raise reraise(type(error), error, _stacktrace)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/util/util.py\", line 38, in reraise\n    raise value.with_traceback(tb)\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 787, in urlopen\n    response = self._make_request(\n               ^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 488, in _make_request\n    raise new_e\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 464, in _make_request\n    self._validate_conn(conn)\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 1093, in _validate_conn\n    conn.connect()\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/connection.py\", line 741, in connect\n    sock_and_verified = _ssl_wrap_socket_and_match_hostname(\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/connection.py\", line 920, in _ssl_wrap_socket_and_match_hostname\n    ssl_sock = ssl_wrap_socket(\n               ^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/util/ssl_.py\", line 460, in ssl_wrap_socket\n    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/util/ssl_.py\", line 504, in _ssl_wrap_socket_impl\n    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/ssl.py\", line 455, in wrap_socket\n    return self.sslsocket_class._create(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/ssl.py\", line 1042, in _create\n    self.do_handshake()\n  File \"/usr/lib/python3.12/ssl.py\", line 1320, in do_handshake\n    self._sslobj.do_handshake()\nurllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 344, in from_call\n    result: TResult | None = func()\n                             ^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 246, in <lambda>\n    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_hooks.py\", line 512, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    raise exception\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/_pytest/logging.py\", line 850, in pytest_runtest_call\n    yield\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/_pytest/capture.py\", line 900, in pytest_runtest_call\n    return (yield)\n            ^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/_pytest/skipping.py\", line 263, in pytest_runtest_call\n    return (yield)\n            ^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 178, in pytest_runtest_call\n    item.runtest()\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/_pytest/python.py\", line 1671, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_hooks.py\", line 512, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    raise exception\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/_pytest/python.py\", line 157, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pytest_asyncio/plugin.py\", line 529, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.12/asyncio/base_events.py\", line 687, in run_until_complete\n    return future.result()\n           ^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/tests/integration/test_charm.py\", line 76, in test_deploy\n    res = session.get(\n          ^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/requests/sessions.py\", line 602, in get\n    return self.request(\"GET\", url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/requests/sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/requests/sessions.py\", line 724, in send\n    history = [resp for resp in gen]\n              ^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/requests/sessions.py\", line 265, in resolve_redirects\n    resp = self.send(\n           ^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/requests/sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/tests/integration/helper.py\", line 71, in send\n    return super().send(request, stream, timeout, verify, cert, proxies)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/requests/adapters.py\", line 659, in send\n    raise ConnectionError(err, request=request)\nrequests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":true,"beforeStages":[{"name":"event_loop","time":{"start":1761227569276,"stop":1761227569276,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"tmp_path_factory","time":{"start":1761227569276,"stop":1761227569276,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"pytestconfig","time":{"start":1761227569277,"stop":1761227569277,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ops_test","time":{"start":1761227569277,"stop":1761227569501,"duration":224},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"charm","time":{"start":1761227569277,"stop":1761227569277,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"model","time":{"start":1761227569502,"stop":1761227569502,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"application","time":{"start":1761227569502,"stop":1761227610648,"duration":41146},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"certificate_provider_application","time":{"start":1761227610648,"stop":1761227651369,"duration":40721},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"certificate_provider_application_name","time":{"start":1761227610648,"stop":1761227610648,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"configured_application_with_tls","time":{"start":1761227651370,"stop":1761227715726,"duration":64356},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ingress_requirer_application_name","time":{"start":1761227715726,"stop":1761227715726,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ingress_requirer_application","time":{"start":1761227715726,"stop":1761227717889,"duration":2163},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"lightkube_client","time":{"start":1761227717889,"stop":1761227717908,"duration":19},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"kube_config","time":{"start":1761227717889,"stop":1761227717889,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"abort_on_fail","time":{"start":1761227717909,"stop":1761227717909,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"description":"Deploy the charm together with related charms.\n\n    Assert on the unit status before any relations/configurations take place.\n    ","status":"broken","statusMessage":"requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","statusTrace":"Traceback (most recent call last):\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 787, in urlopen\n    response = self._make_request(\n               ^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 488, in _make_request\n    raise new_e\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 464, in _make_request\n    self._validate_conn(conn)\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 1093, in _validate_conn\n    conn.connect()\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/connection.py\", line 741, in connect\n    sock_and_verified = _ssl_wrap_socket_and_match_hostname(\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/connection.py\", line 920, in _ssl_wrap_socket_and_match_hostname\n    ssl_sock = ssl_wrap_socket(\n               ^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/util/ssl_.py\", line 460, in ssl_wrap_socket\n    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/util/ssl_.py\", line 504, in _ssl_wrap_socket_impl\n    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/ssl.py\", line 455, in wrap_socket\n    return self.sslsocket_class._create(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/ssl.py\", line 1042, in _create\n    self.do_handshake()\n  File \"/usr/lib/python3.12/ssl.py\", line 1320, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/requests/adapters.py\", line 644, in send\n    resp = conn.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 841, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/util/retry.py\", line 474, in increment\n    raise reraise(type(error), error, _stacktrace)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/util/util.py\", line 38, in reraise\n    raise value.with_traceback(tb)\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 787, in urlopen\n    response = self._make_request(\n               ^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 488, in _make_request\n    raise new_e\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 464, in _make_request\n    self._validate_conn(conn)\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 1093, in _validate_conn\n    conn.connect()\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/connection.py\", line 741, in connect\n    sock_and_verified = _ssl_wrap_socket_and_match_hostname(\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/connection.py\", line 920, in _ssl_wrap_socket_and_match_hostname\n    ssl_sock = ssl_wrap_socket(\n               ^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/util/ssl_.py\", line 460, in ssl_wrap_socket\n    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/urllib3/util/ssl_.py\", line 504, in _ssl_wrap_socket_impl\n    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/ssl.py\", line 455, in wrap_socket\n    return self.sslsocket_class._create(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/ssl.py\", line 1042, in _create\n    self.do_handshake()\n  File \"/usr/lib/python3.12/ssl.py\", line 1320, in do_handshake\n    self._sslobj.do_handshake()\nurllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 344, in from_call\n    result: TResult | None = func()\n                             ^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 246, in <lambda>\n    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_hooks.py\", line 512, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    raise exception\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/_pytest/logging.py\", line 850, in pytest_runtest_call\n    yield\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/_pytest/capture.py\", line 900, in pytest_runtest_call\n    return (yield)\n            ^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/_pytest/skipping.py\", line 263, in pytest_runtest_call\n    return (yield)\n            ^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 178, in pytest_runtest_call\n    item.runtest()\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/_pytest/python.py\", line 1671, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_hooks.py\", line 512, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    raise exception\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/_pytest/python.py\", line 157, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/pytest_asyncio/plugin.py\", line 529, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.12/asyncio/base_events.py\", line 687, in run_until_complete\n    return future.result()\n           ^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/tests/integration/test_charm.py\", line 76, in test_deploy\n    res = session.get(\n          ^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/requests/sessions.py\", line 602, in get\n    return self.request(\"GET\", url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/requests/sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/requests/sessions.py\", line 724, in send\n    history = [resp for resp in gen]\n              ^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/requests/sessions.py\", line 265, in resolve_redirects\n    resp = self.send(\n           ^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/requests/sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/tests/integration/helper.py\", line 71, in send\n    return super().send(request, stream, timeout, verify, cert, proxies)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ubuntu/actions-runner/_work/gateway-api-integrator-operator/gateway-api-integrator-operator/.tox/integration/lib/python3.12/site-packages/requests/adapters.py\", line 659, in send\n    raise ConnectionError(err, request=request)\nrequests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","steps":[],"attachments":[{"uid":"4258804e1f17cba6","name":"log","source":"4258804e1f17cba6.txt","type":"text/plain","size":8152}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"abort_on_fail::0","time":{"start":1761227780199,"stop":1761227780200,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ops_test::finalizer","time":{"start":1761227780201,"stop":1761227780618,"duration":417},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"application::finalizer","time":{"start":1761227780201,"stop":1761227780201,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::2","time":{"start":1761227780619,"stop":1761227780619,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_close_event_loop","time":{"start":1761227780619,"stop":1761227780619,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_provide_clean_event_loop","time":{"start":1761227780619,"stop":1761227780619,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"abort_on_fail"},{"name":"tag","value":"asyncio"},{"name":"parentSuite","value":"tests.integration"},{"name":"suite","value":"test_charm"},{"name":"host","value":"github-runner"},{"name":"thread","value":"18248-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.integration.test_charm"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"67a6a6a610eab8d9","status":"unknown","time":{}}],"categories":[{"name":"Test defects","matchedStatuses":[]}],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":2,"unknown":0,"total":4},"items":[{"uid":"47f47115c78b956c","reportUrl":"../535//#testresult/47f47115c78b956c","status":"broken","statusDetails":"requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","time":{"start":1761202066048,"stop":1761202127442,"duration":61394}},{"uid":"b3408d00240d4d29","reportUrl":"../534//#testresult/b3408d00240d4d29","status":"passed","time":{"start":1761201641430,"stop":1761201693736,"duration":52306}},{"uid":"3eca5b986c35dd38","reportUrl":"../530//#testresult/3eca5b986c35dd38","status":"passed","time":{"start":1761042678997,"stop":1761042732094,"duration":53097}}]},"tags":["asyncio","abort_on_fail"]},"source":"d7dce9eb7ac6394c.json","parameterValues":[]}